[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.6.12"
remappings = [
    "forge-std/=lib/forge-std/src/",
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]